### ISSUE TITLE
Implement the handling of tables in translation files

### ISSUE THREAD

**Issue by zedtux** [onesky/onesky-rails#23]
Given the base language of the application is English
And the application is translated in French
And an English translation YAML file contains a table as the following:

``` yaml
en:
  days:
    - Monday
    - Tuesday
    - Wednesday
    - Tuesday
    - Friday
    - Saturday
    - Sunday
```

When I upload this file to the OneSky platform
And I download the French translation files
Then I see the following file:

``` yaml
fr:
  days:
    ? "1"
    : Mardi
    ? "0"
    : Lundi
    ? "2"
    : Mercredi
    ? "3"
    : Jeudi
    ? "4"
    : Vendredi
    ? "5"
    : Samedi
    ? "6"
    : Dimanche
```

While I expect to see the following file:

``` yaml
fr:
  days:
    - Lundi
    - Mardi
    - Mercredi
    - Jeudi
    - Vendredi
    - Samedi
    - Dimanche
```
